# Importation et exploration

In [46]:
import pandas as pd

In [47]:
df = pd.read_csv("store1.csv")

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   str
 3   Ship Date      9800 non-null   str
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB

# Nettoyage

In [48]:
df.duplicated()

# Corriger les types de colonnes (dates, numériques, catégories)

df["Order Date"] =  pd.to_datetime(df["Order Date"],format="%d/%m/%Y")
df["Ship Date"] = pd.to_datetime(df["Ship Date"],format="%d/%m/%Y")
df["Postal Code"] = df["Postal Code"].astype("Int64")

df = df.dropna()

df.info()

<class 'pandas.DataFrame'>
Index: 9789 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9789 non-null   int64
 1   Order ID       9789 non-null   str
 2   Order Date     9789 non-null   datetime64[us]
 3   Ship Date      9789 non-null   datetime64[us]
 4   Ship Mode      9789 non-null   str
 5   Customer ID    9789 non-null   str
 6   Customer Name  9789 non-null   str
 7   Segment        9789 non-null   str
 8   Country        9789 non-null   str
 9   City           9789 non-null   str
 10  State          9789 non-null   str
 11  Postal Code    9789 non-null   Int64
 12  Region         9789 non-null   str
 13  Product ID     9789 non-null   str
 14  Category       9789 non-null   str
 15  Sub-Category   9789 non-null   str
 16  Product Name   9789 non-null   str
 17  Sales          9789 non-null   float64
dtypes: Int64(1), datetime64[us](2), float64(1), int64(1), str(13)
memory usage: 1.4 MB

In [49]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

In [50]:
coln_categorie = [
"Ship Mode","Segment","Country",
"City","State","Region","Category","Sub-Category"
]
for col in coln_categorie:
    df[col]=df[col].astype('category')
print(df.dtypes)

Row ID                    int64
Order ID                    str
Order Date       datetime64[us]
Ship Date        datetime64[us]
Ship Mode              category
Customer ID                 str
Customer Name               str
Segment                category
Country                category
City                   category
State                  category
Postal Code               Int64
Region                 category
Product ID                  str
Category               category
Sub-Category           category
Product Name                str
Sales                   float64
dtype: object

# Transformation et feature engineering

In [58]:
# Extraire des informations temporelles : année, mois, trimestre

df["Annee"]= df["Order Date"].dt.year
df["Mois"]= df["Order Date"].dt.month
df["Trimestre"]= df["Order Date"].dt.quarter
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sales,Annee,Mois,Trimestre,cout,profit,taux_profit,ratio,segmentation,dliv
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2017,11,4,209.5680,52.3920,20.0,0.2,trés haut,3
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,2017,11,4,585.5520,146.3880,20.0,0.2,trés haut,3
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2017,6,2,11.6960,2.9240,20.0,0.2,moyen,4
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,2016,10,4,766.0620,191.5155,20.0,0.2,trés haut,7
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2016,10,4,17.8944,4.4736,20.0,0.2,moyen,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,2017-05-21,2017-05-28,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,...,3.7980,2017,5,2,3.0384,0.7596,20.0,0.2,moyen,7
9796,9797,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,10.3680,2016,1,1,8.2944,2.0736,20.0,0.2,moyen,5
9797,9798,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,235.1880,2016,1,1,188.1504,47.0376,20.0,0.2,trés haut,5
9798,9799,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,26.3760,2016,1,1,21.1008,5.2752,20.0,0.2,moyen,5
9799,9800,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,10.3840,2016,1,1,8.3072,2.0768,20.0,0.2,moyen,5

In [52]:
# les métriques:

df["cout"]= df["Sales"]*0.8
df["profit"]= df["Sales"]-df["cout"]
df["taux_profit"]= df["profit"]/df["Sales"]*100
df["ratio"]= df["profit"]/df["Sales"]
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Annee,Mois,Trimestre,cout,profit,taux_profit,ratio
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2017,11,4,209.5680,52.3920,20.0,0.2
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,2017,11,4,585.5520,146.3880,20.0,0.2
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2017,6,2,11.6960,2.9240,20.0,0.2
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,2016,10,4,766.0620,191.5155,20.0,0.2
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2016,10,4,17.8944,4.4736,20.0,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,2017-05-21,2017-05-28,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,...,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980,2017,5,2,3.0384,0.7596,20.0,0.2
9796,9797,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680,2016,1,1,8.2944,2.0736,20.0,0.2
9797,9798,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,Phones,GE 30524EE4,235.1880,2016,1,1,188.1504,47.0376,20.0,0.2
9798,9799,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,Phones,Anker 24W Portable Micro USB Car Charger,26.3760,2016,1,1,21.1008,5.2752,20.0,0.2
9799,9800,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840,2016,1,1,8.3072,2.0768,20.0,0.2

In [53]:
from utils import segmentation


df["segmentation"] = df["Sales"].map(segmentation)
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product Name,Sales,Annee,Mois,Trimestre,cout,profit,taux_profit,ratio,segmentation
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bush Somerset Collection Bookcase,261.9600,2017,11,4,209.5680,52.3920,20.0,0.2,trés haut
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,2017,11,4,585.5520,146.3880,20.0,0.2,trés haut
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Self-Adhesive Address Labels for Typewriters b...,14.6200,2017,6,2,11.6960,2.9240,20.0,0.2,moyen
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,2016,10,4,766.0620,191.5155,20.0,0.2,trés haut
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Eldon Fold 'N Roll Cart System,22.3680,2016,10,4,17.8944,4.4736,20.0,0.2,moyen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,2017-05-21,2017-05-28,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,...,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980,2017,5,2,3.0384,0.7596,20.0,0.2,moyen
9796,9797,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,"BIC Brite Liner Highlighters, Chisel Tip",10.3680,2016,1,1,8.2944,2.0736,20.0,0.2,moyen
9797,9798,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,GE 30524EE4,235.1880,2016,1,1,188.1504,47.0376,20.0,0.2,trés haut
9798,9799,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,Anker 24W Portable Micro USB Car Charger,26.3760,2016,1,1,21.1008,5.2752,20.0,0.2,moyen
9799,9800,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,SanDisk Cruzer 4 GB USB Flash Drive,10.3840,2016,1,1,8.3072,2.0768,20.0,0.2,moyen

In [54]:
# Délais de livraison:

df["dliv"]= (df["Ship Date"]-df["Order Date"]).dt.days
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sales,Annee,Mois,Trimestre,cout,profit,taux_profit,ratio,segmentation,dliv
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2017,11,4,209.5680,52.3920,20.0,0.2,trés haut,3
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,2017,11,4,585.5520,146.3880,20.0,0.2,trés haut,3
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2017,6,2,11.6960,2.9240,20.0,0.2,moyen,4
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,2016,10,4,766.0620,191.5155,20.0,0.2,trés haut,7
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2016,10,4,17.8944,4.4736,20.0,0.2,moyen,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,2017-05-21,2017-05-28,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,...,3.7980,2017,5,2,3.0384,0.7596,20.0,0.2,moyen,7
9796,9797,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,10.3680,2016,1,1,8.2944,2.0736,20.0,0.2,moyen,5
9797,9798,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,235.1880,2016,1,1,188.1504,47.0376,20.0,0.2,trés haut,5
9798,9799,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,26.3760,2016,1,1,21.1008,5.2752,20.0,0.2,moyen,5
9799,9800,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,10.3840,2016,1,1,8.3072,2.0768,20.0,0.2,moyen,5

In [55]:
# Ventes par catégorie/ région:

vent_par_catg= df.groupby("Category")["Sales"].sum().sort_values(ascending=False)
vent_par_rég= df.groupby("Region")["Sales"].sum().sort_values(ascending=False)
print(vent_par_catg)
print(vent_par_rég)

Category
Technology         825856.1130
Furniture          723538.4757
Office Supplies    703212.8240
Name: Sales, dtype: float64
Region
West       710219.6845
East       660589.3560
Central    492646.9132
South      389151.4590
Name: Sales, dtype: float64

In [56]:
df.to_csv("ex.csv")